name: Setup

description: Setup

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '20.10.0'
  daemon:
    description: Daemon name
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup
      with:
        node_version: ${{ inputs.node_version }}
    - name: Install
      run: |
        cd ${{ inputs.daemon }}
        npm install
      shell: bash
