name: Setup

description: Setup

inputs:
  bun_version:
    description: Bun version
    required: false
    default: '1.2.19'
  daemon:
    description: Daemon name
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup
      with:
        bun_version: ${{ inputs.bun_version }}
    # Required for building the darwin appdmg.
    - name: Install Python 3.11.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    - name: Install
      run: bun install
      shell: bash
