name: Setup

description: Setup

inputs:
  node_version:
    description: Node.js version
    required: false
    default: 23.11.0

runs:
  using: composite
  steps:
    - name: git user config
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org
    - name: Install root dependencies
      run: |
        npm install --workspaces=false
      shell: bash
