name: Setup

description: Setup

inputs:
  bun_version:
    description: Bun version
    required: false
    default: 1.2.18

runs:
  using: composite
  steps:
    - name: git user config
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun_version }}
    - name: Install root dependencies
      run: |
        bun install
      shell: bash
