// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ConfigAndBinaryDirectoryPath():Promise<string>;

export function ConfigAndBinaryPath():Promise<string>;

export function DefaultDataPath():Promise<string>;

export function DownloadRelease():Promise<void>;

export function GenerateSeed():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetInstalledVersion():Promise<string>;

export function GetLatestVersion():Promise<string>;

export function IsConfigured():Promise<boolean>;

export function IsDaemonRunning():Promise<boolean>;

export function IsValidPhrase(arg1:string):Promise<boolean>;

export function NeedsDownload():Promise<boolean>;

export function Open(arg1:string):Promise<void>;

export function OpenBrowser():Promise<void>;

export function OpenConfigDirectory():Promise<void>;

export function OpenConfigFile():Promise<void>;

export function OpenDataDirectory():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartDaemon(arg1:boolean):Promise<void>;

export function StopDaemon():Promise<void>;
