// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadRelease() {
  return window['go']['main']['App']['DownloadRelease']();
}

export function GenerateSeed() {
  return window['go']['main']['App']['GenerateSeed']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function NeedsDownload() {
  return window['go']['main']['App']['NeedsDownload']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function ValidConfig(arg1) {
  return window['go']['main']['App']['ValidConfig'](arg1);
}
