// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigAndBinaryDirectoryPath() {
  return window['go']['main']['App']['ConfigAndBinaryDirectoryPath']();
}

export function ConfigAndBinaryPath() {
  return window['go']['main']['App']['ConfigAndBinaryPath']();
}

export function DefaultDataPath() {
  return window['go']['main']['App']['DefaultDataPath']();
}

export function DownloadRelease() {
  return window['go']['main']['App']['DownloadRelease']();
}

export function GenerateSeed() {
  return window['go']['main']['App']['GenerateSeed']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInstalledVersion() {
  return window['go']['main']['App']['GetInstalledVersion']();
}

export function GetLatestVersion() {
  return window['go']['main']['App']['GetLatestVersion']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function IsDaemonRunning() {
  return window['go']['main']['App']['IsDaemonRunning']();
}

export function IsValidPhrase(arg1) {
  return window['go']['main']['App']['IsValidPhrase'](arg1);
}

export function NeedsDownload() {
  return window['go']['main']['App']['NeedsDownload']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function OpenConfigDirectory() {
  return window['go']['main']['App']['OpenConfigDirectory']();
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function OpenDataDirectory() {
  return window['go']['main']['App']['OpenDataDirectory']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartDaemon(arg1) {
  return window['go']['main']['App']['StartDaemon'](arg1);
}

export function StopDaemon() {
  return window['go']['main']['App']['StopDaemon']();
}
