// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function DownloadRelease():Promise<void>;

export function GenerateSeed():Promise<string>;

export function LoadConfig():Promise<config.Config>;

export function NeedsDownload():Promise<boolean>;

export function OpenBrowser(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function Start():Promise<void>;

export function ValidConfig(arg1:config.Config):Promise<boolean>;
