// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function DownloadRelease():Promise<void>;

export function GenerateSeed():Promise<string>;

export function NeedsConfig():Promise<boolean>;

export function NeedsDownload():Promise<boolean>;

export function OpenBrowser():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartDaemon(arg1:boolean):Promise<void>;
