name: Update daemons PR

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  repository_dispatch:
    types: [daemons-update]
  # Enable manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  daemons-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: renterd
        uses: ./.github/actions/daemon-update
        with:
          daemon: renterd
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: hostd
        uses: ./.github/actions/daemon-update
        with:
          daemon: hostd
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: walletd
        uses: ./.github/actions/daemon-update
        with:
          daemon: walletd
          token: ${{ secrets.GITHUB_TOKEN }}
