name: Update release PR or publish GitHub release

on:
  push:
    branches:
      - master

concurrency: commits-to-master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          bun_version: 1.2.19
      - name: Install @changesets/cli
        run: bun install @changesets/cli
        shell: bash
      - name: Update release pull request or publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: 'chore: release packages'
          publish: bun run release
      - name: Publish electron apps
        # if a release was published, publish the electron apps
        if: steps.changesets.outputs.published == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: siafoundation/desktop
          event-type: publish
