name: Update release PR or publish GitHub release

on:
  push:
    branches:
      - master

concurrency: commits-to-master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup
        uses: ./.github/actions/setup
      - name: Update release pull request or publish
        id: changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: 'chore: release packages'
          # The following scripts temporarily add the workspaces key to the
          # package.json. This is necessary because changesets requires workspaces
          # to find projects but we otherwise want to manage the projects in this
          # repo independently.
          # - 'version' also removes the workspaces key after so that the change
          # to package.json is not included in the changeset pull request.
          # - 'release' does not remove the workspaces key because this would
          # make changesets try to publish as a single package repo, and it does
          # not commit the file anyway.
          publish: bun run release
          version: bun run version
      - name: Publish electron apps
        # if a release was published, publish the electron apps
        if: steps.changesets.outputs.published == 'true'
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: siafoundation/desktop
          event-type: publish
