name: Update release PR or publish GitHub release

on:
  push:
    branches:
      - master

concurrency: commits-to-master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 20.10.0
      - name: Install @changesets/cli
        run: npm install -g @changesets/cli
        shell: bash
      # Copy publish.json to package.json so that changesets can find it
      # workspace projects.
      # Electron has issues with npm and yarn package hoisting in a monorepo
      # so the repo is set up as individual projects with no root package.json.
      - name: Copy publish.json to package.json
        run: cp release.json package.json
        shell: bash
      - name: Update release pull request or publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: 'chore: release packages'
          publish: npm run release
      - name: Publish electron apps
        # if a release was published, publish the electron apps
        if: steps.changesets.outputs.published == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: siafoundation/desktop
          event-type: publish
