name: Update release PR or publish GitHub release

on:
  push:
    branches:
      - master

concurrency: commits-to-master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 20.10.0
      - name: Update release pull request or publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: 'chore: release packages'
          publish: yarn run release
      - name: Publish electron apps
        # if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/SiaFoundation/desktop/actions/workflows/publish.yml/dispatches \
            -d '{"ref":"master"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
